parameters:
    qandidate.toggle.manager.class: Qandidate\Toggle\ToggleManager
    qandidate.toggle.collection.in_memory.class: Qandidate\Toggle\ToggleCollection\InMemoryCollection
    qandidate.toggle.collection.serializer.in_memory.class: Qandidate\Toggle\Serializer\InMemoryCollectionSerializer
    qandidate.toggle.collection.predis.class: Qandidate\Toggle\ToggleCollection\PredisCollection
    qandidate.toggle.user_context_factory.class: Qandidate\Bundle\ToggleBundle\Context\UserContextFactory
    qandidate.toggle.twig_extension.class: Qandidate\Bundle\ToggleBundle\Twig\ToggleTwigExtension
    qandidate.toggle.toggle.listener.class: Qandidate\Bundle\ToggleBundle\EventListener\ToggleListener
    qandidate.toggle.context.class: Qandidate\Toggle\Context
    qandidate.toggle.data_collector.toggle_collector.class: Qandidate\Bundle\ToggleBundle\DataCollector\ToggleCollector

services:
    qandidate.toggle.collection.in_memory:
        class: '%qandidate.toggle.collection.in_memory.class%'

    qandidate.toggle.collection.serializer.in_memory:
        class: '%qandidate.toggle.collection.serializer.in_memory.class%'

    qandidate.toggle.manager:
        class: '%qandidate.toggle.manager.class%'
        public: true
        arguments:
            - '@qandidate.toggle.collection'

    qandidate.toggle.user_context_factory:
        class: '%qandidate.toggle.user_context_factory.class%'
        public: true
        arguments:
            - '@security.token_storage'

    qandidate.toggle.twig_extension:
        class: '%qandidate.toggle.twig_extension.class%'
        arguments:
            - '@qandidate.toggle.manager'
            - '@qandidate.toggle.context_factory'
        tags:
            - { name: twig.extension }

    qandidate.toggle.context:
        class: '%qandidate.toggle.context.class%'
        factory: ['@qandidate.toggle.context_factory', createContext]

    qandidate.toggle.toggle.listener:
        class: '%qandidate.toggle.toggle.listener.class%'
        arguments:
            - '@qandidate.toggle.manager'
            - '@qandidate.toggle.context'
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    qandidate.toggle.data_collector.toggle_collector:
        class: '%qandidate.toggle.data_collector.toggle_collector.class%'
        arguments:
            - '@qandidate.toggle.manager'
            - '@qandidate.toggle.context_factory'
        tags:
            - { name: data_collector, id: qandidate.toggle_collector, template: '@QandidateToggle\data_collector\toggle.html.twig' }
