language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=5.1.*

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=''
    - php: 7.3
      env: SYMFONY_VERSION=''
    - php: 7.4
      env: SYMFONY_VERSION=''

before_script:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;
  - travis_retry composer update $COMPOSER_FLAGS

script:
  - make test
  - make qa
  - make license
  - make changelog
