language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

env:
  - SYMFONY_VERSION="2.7.*" PREFER_LOWEST='--prefer-lowest'
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

install:
   - composer self-update
   - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --dev
   - composer update --prefer-dist --no-interaction $PREFER_LOWEST

script:
  - phpunit

branches:
  only:
    - master
