name: "CI"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
  schedule:
    - cron: "37 13 * * 1"

jobs:
  tests:
    name: "Run tests"
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        php-version: # https://www.php.net/supported-versions.php
          - "8.1"
          - "8.2"
        symfony-version: # https://symfony.com/releases
          - "6.1"
          - "6.2"
    env:
      SYMFONY_REQUIRE: "${{ matrix.symfony-version }}"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
        env:
          fail-fast: true
      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict --no-interaction --ansi"
      - name: "Install symfony/flex" # see https://symfony.com/doc/current/bundles/best_practices.html#require-a-specific-symfony-version
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
      - name: "Install dependencies with Composer"
        run: composer update --prefer-dist --no-progress
      - name: "Run tests"
        run: "make test"

  coding-standards:
    name: "Coding standards"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "none"
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
      - name: "Check coding standards"
        run: "make php-cs-fixer-ci"
      - name: Create Pull Request
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Apply coding standards
          branch: php-cs-fixer
          delete-branch: true
          title: 'Apply coding standards'
          draft: false
          base: master

  static-analysis:
    name: "Static analysis"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "none"
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
      - name: "Run PHPStan"
        run: "make phpstan"
